### ISSUE TITLE
Unable to access site: "Application error: a client-side exception has occurred (see the browser console for more information)."

### ISSUE THREAD

**Issue by Artilugio1** [helium/helium-vote#136]
Hello

Having a problem entering the new HeliumVote site (https://heliumvote.com/hnt).
The landing page flashes up for a brief moment before the following message appears:

Application error: a client-side exception has occurred (see the browser console for more information).

I've attached console log (which means absolutely nothing to me). Others in Discord have encountered same problem

[heliumvote.com-1711444813837.log](https://github.com/helium/helium-vote/files/14755868/heliumvote.com-1711444813837.log)

EDIT: Just to add that the same issue arises with multiple browsers - Chrome, Brave, Firefox - and opening in a private window has no effect.

**Comment by abhay** [comment]
are you still seeing this issue?

**Comment by Artilugio1** [comment]
> are you still seeing this issue?

Hey there. No, everything looks fine now (and the page design is a big improvement over the old version).
