### ISSUE TITLE
add ledger CLI as another way to vote

### ISSUE THREAD

**Issue by cokes518** [helium/helium-vote#19]
when we get the burn transaction support in the ledger app, we'll need to include the command on the vote page.

by default, we'll show the app and the CLI command.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/19331274/138141225-fe37cff5-49e2-477e-a101-3a1d88fb7fea.png">

**Comment by madninja** [comment]
I guess you're showing how to do this in air gapped CLI wallets? The instructions would be harder
