### ISSUE TITLE
Transferred HNT instead of burning to vote

### ISSUE THREAD

**Issue by FezzFest** [helium/helium-vote#30]
I accidentally transferred HNT to the wallet specified on heliumvote.com instead of burning it.
https://explorer.helium.com/accounts/134UcXhcGD1fxR3XrA3rgXXiQCjNFiB8MbnxsTX8z1iv3CQ52Zs
Turns out that doesn't work. Can someone at least register this as a vote?

(my apologies for opening a github issue for this, but I didn't know where else to ask)

**Comment by jthiller** [comment]
Payment has been reversed, minus the transaction fee. 
Thanks for filing the issue here.
