### ISSUE TITLE
Waste of hnt for smaller wallets

### ISSUE THREAD

**Issue by liamgibbins** [helium/helium-vote#48]
This is such an bias voting system and should be based on entities that make up the network for it to be a fair community driven system.

I am guessing that it's based like this so that it fits a business model and votes get pushed through in regards to this business model.

So unfair and not a true community driven system.
It just gives you the illustration that your vote counts when it doesnt

**Comment by jamiew** [comment]
Always happy to field better ideas for better voting structures or models for community partipipation. Discord or some of the threads in https://github.com/helium/hip is a good start. There are several voting/governance related proposals already.

Closing this issue as this isn't a discussion forum. Thanks
